### ISSUE TITLE
CCF搜索误报

### ISSUE THREAD

**Issue by buttercannfly** [USTC3418Lab/Lab418Site#11]
像AsiaCCS与CCS使用的url很相似(在中国学会那个pdf里url相同)，存在着将AsiaCCS报为A类的误报，后面考虑使用别人已经处理好的会议表格

**Comment by EricJeffrey** [comment]
通过延长预处理的会议地址url( `https://dblp.uni-trier.de/db/conf/ccs/`-> `https://dblp.uni-trier.de/db/conf/ccs/ccs` ) 以及使用 `startsWith` 方法应该可以解决

**Comment by buttercannfly** [comment]
emm没法弄了这个，现在使用set存ABC类的url，如果用startswith，又变成了需要便利，所以说asiaccs就尼玛老鼠屎

**Comment by EricJeffrey** [comment]
🆗那就不管了
