### ISSUE TITLE
临时网盘 

### ISSUE THREAD

**Issue by EricJeffrey** [USTC3418Lab/Lab418Site#2]
临时网盘，列出目录，能够下载和上传文件。

- 文件夹需要挂载到容器内
- 以目录形式列出
- 左侧文件列表右侧上传区域

将目录挂载到容器中，即可保持文件不被删除（否则容器被删除后文件就无了）

需要一些设计
- 文件传输前端如何实现（似乎有文件选择器？
- 后端如何实现（FileOutputStream?
- 文件大小限制？
- 前端展示样式？列表？每一级目录是否需要更改`location`
....

**Comment by EricJeffrey** [comment]
大致搜了一下，后端的话 [spring.io](https://spring.io/guides/gs/uploading-files/)，[springboot-filedownload](https://stackoverflow.com/questions/35680932/download-a-file-from-spring-boot-rest-service)，都有例子，上传就是表单的文件POST，下载的话使用`Resource`相关的类。

前端的话，antd有[上传文件](https://ant.design/components/upload-cn/)的组件也有[树形列表](https://ant.design/components/tree-cn/)的组件，挺方便的。

**Comment by EricJeffrey** [comment]
@buttercannfly 可以稍微看一下

**Comment by EricJeffrey** [comment]
额，好像还需要考虑一些情况，比如
1. 创建文件夹？ ✅
2. 多个文件下载？ ❎ 浏览器里面多文件下载挺麻烦的
3. 删除某个文件或文件夹？✅

我的看法的话，
1. 可以创建文件夹，在树形结构第一行旁边显示一个新建文件夹按钮
2. 上传的时候，根据树形目录的选中项（可以使用checkbox之类的表示）确定上传的位置
    - 上传和下载的时候都指定一个路径的参数，表示目标文件夹
3. 允许删除文件或文件夹🙄 删除操作并不是真的删除，而是将其移动到指定位置`.deleted/`，但是这也表示不能创建名为`.deleted`的文件夹
4. 提供一个默认的临时文件夹`temp/`
。。。。。。

**Comment by EricJeffrey** [comment]
下载的话参考 [这个](https://stackoverflow.com/questions/20508788/do-i-need-content-type-application-octet-stream-for-file-download/20509354#20509354)和 [这个](https://stackoverflow.com/questions/50694881/how-to-download-file-in-react-js)，需要后端处理一下，配置响应头，读取文件然后把responsebody设置成文件内容

**Comment by buttercannfly** [comment]
我裂开 之前没注意到这个issue

**Comment by buttercannfly** [comment]
也就是说，后端拿到文件名，读出文件内容返回给前端吗

**Comment by buttercannfly** [comment]
不太对 前端的a标签不是就可以提供下载了吗

**Comment by buttercannfly** [comment]
那后端拿到网盘文件夹内的所有文件，返回给前端

**Comment by EricJeffrey** [comment]
🙄 额，这个你得想想的 😂 别想的太简单了

**Comment by EricJeffrey** [comment]
可以看下我上面写的那几个链接

**Comment by buttercannfly** [comment]
ok

**Comment by EricJeffrey** [comment]
接口的话可能需要
- 获取所有文件内容，GET 方式，返回值为
  ```
  {
      code(number),
      message(str), 
      data: {
          name(str),
          leaf(false)
          child: [
              name(str),
              leaf(bool),
              child: [...]
          ]
      }
  }
  ```
  其中`leaf`表示是否为叶子，如果为叶子则忽略`child`
- 上传单个文件，POST 表单提交，返回值 `{code, message}`
- 上传多个文件，POST 表单提交，返回值 `{code, message}` 
- 删除某个文件，POST 表单提交文件名，返回值`{code, message}`
- 下载某个文件，GET方式，参数为文件路径，返回数据为文件流
- 新建文件夹，POST方式，参数为文件夹路径，返回值 `{code, message}`


---------------------------------
先暂时这样，需要尝试实现并考虑接口的变更

**Comment by EricJeffrey** [comment]
data改为的数组嵌套形式

```
{
    code(number),
    message(str), 
    data: [{
        name(str),
        leaf(false)
        child: [
            name(str),
            leaf(bool),
            child: [...]
        ]
    }]
}
```

**Comment by buttercannfly** [comment]
> 接口的话可能需要
> 
> * 获取所有文件内容，GET 方式，返回值为
>   ```
>   {
>       code(number),
>       message(str), 
>       data: {
>           name(str),
>           leaf(false)
>           child: [
>               name(str),
>               leaf(bool),
>               child: [...]
>           ]
>       }
>   }
>   ```
>   
>   
>   其中`leaf`表示是否为叶子，如果为叶子则忽略`child`
> * 上传单个文件，POST 表单提交，返回值 `{code, message}`
> * 删除某个文件，POST 表单提交文件名，返回值`{code, message}`
> * 下载某个文件，GET方式，参数为文件路径，返回数据为文件流
> * 新建文件夹，POST方式，参数为文件夹路径，返回值 `{code, message}`
> 
> 先暂时这样，需要尝试实现并考虑接口的变更
> 
> @buttercannfly 可以看一下接口的概要，后面还要确认一下接口的返回值具体信息

删除是不是一般用的GET方法，传入文件路径即可

**Comment by buttercannfly** [comment]
> 接口的话可能需要
> 
> * 获取所有文件内容，GET 方式，返回值为
>   ```
>   {
>       code(number),
>       message(str), 
>       data: {
>           name(str),
>           leaf(false)
>           child: [
>               name(str),
>               leaf(bool),
>               child: [...]
>           ]
>       }
>   }
>   ```
>   
>   
>   其中`leaf`表示是否为叶子，如果为叶子则忽略`child`
> * 上传单个文件，POST 表单提交，返回值 `{code, message}`
> * 删除某个文件，POST 表单提交文件名，返回值`{code, message}`
> * 下载某个文件，GET方式，参数为文件路径，返回数据为文件流
> * 新建文件夹，POST方式，参数为文件夹路径，返回值 `{code, message}`
> 
> 先暂时这样，需要尝试实现并考虑接口的变更
> 
> @buttercannfly 可以看一下接口的概要，后面还要确认一下接口的返回值具体信息

下载这个，如果我只是将文件路径传给前端，前端用a标签的话，用户不是也能进行下载吗，这种理解是不是有点问题。

**Comment by EricJeffrey** [comment]
@buttercannfly 删除这个无所谓了，实际上危险一点的操作一般都会用POST，因为POST的内容是加密过的，不会直接暴露接口。
下载的话。前端a标签没错。但是a标签用户点击之后发生的操作是：
```
浏览器向a标签的链接发送get请求
服务器响应对应的请求，响应头指出响应体为某种类型的文件或不知道类型的二进制文件
浏览器收到响应，发现这种文件能显示（图片）或者不能显示（二进制）--- 浏览器直接显示或者弹出下载框
```
你可以先试着写个GET的接口 demo之类的试一下就知道了啊，把static里面的`index.html`换成自己的html文件就能测试了

**Comment by EricJeffrey** [comment]
springboot只知道他自己的 `static` 目录下的 *静态文件*，而网盘是在spring boot或这tomcat外部的内容，他们不知道的（也许能告诉他们

**Comment by EricJeffrey** [comment]
前端的话这样就OK了，后端确定如何实现然后就可以考虑接口具体的数值和格式了

![image](https://user-images.githubusercontent.com/33823695/90600629-7ef8ea00-e229-11ea-934b-7d13da3098ef.png)

目前主要是确定下前端和后端的实现，知道如何实现才能定接口。至于上线无所谓不着急的。

**Comment by EricJeffrey** [comment]
删除文件夹需要递归删除子目录文件，所以忽略该接口。

**Comment by buttercannfly** [comment]
/cloud-disk这个接口，我给他的返回值是不包含这个文件夹名的，也就是上面说的title:"clouddisk"，现在的返回值是你所示的clouddisk下的children

**Comment by EricJeffrey** [comment]
额，那这样吧，这几个接口的话，因为返回值什么的也确定了不需要改，就说一下相对路径绝对路径的问题吧。
- 删除或下载文件`/lab418/clouddisk/tmp/abc.txt`的时候应该传递的路径参数是什么？
- 向文件夹`/lab418/clouddisk/tmp/`上传文件或新建文件夹时应该传递的路径参数？

@buttercannfly

**Comment by buttercannfly** [comment]
- 删除/lab418/clouddisk/tmp/abc.txt传递参数tmp/abc.txt
- 下载/lab418/clouddisk/tmp/abc.txt传递参数tmp/abc.txt
- 向文件夹上传文件传递参数：file：文件，dir：tmp
- 向文件夹新建文件夹传递参数:  filepath : tmp/new_folder

**Comment by EricJeffrey** [comment]
OK
