### ISSUE TITLE
website address of the laboratory? 

### ISSUE THREAD

**Issue by FuSiry** [USTC3418Lab/Lab418Site#23]
Can you give me the website address of the laboratory? Thank you.

**Comment by EricJeffrey** [comment]
Sorry we can't give the address to you as it's not meant to be a public site. You could deploy it on your own server though.

**Comment by FuSiry** [comment]
Ok, thank you very much! If you can, you can show some interfaces of some websites, so that we can know whether it meets our expectations before using it

**Comment by FuSiry** [comment]
> Sorry we can't give the address to you as it's not meant to be a public site. You could deploy it on your own server though.

Ok, thank you very much! If you can, you can show some interfaces of some websites, so that we can know whether it meets our expectations before using it

**Comment by EricJeffrey** [comment]
README里面写了接口
it's already showed in the README.MD
另外，网站功能比较杂乱并且很久没有维护了
Also, functions of the website are messy and haven't been maintained for a long time.
